- name: Config for NFS server 
  hosts: pi #(can use any host or group of hosts)
  tasks:
    - name: install nfs server for Debian/Ubuntu
      ansible.builtin.package:
        name: nfs-kernel-server #(if using Debian/Ubuntu)
        state: present
      when: ansible_facts["os_family"] == "Debian"
    - name: install nfs server for RHEL/CentOS
      ansible.builtin.package:
        name: nfs-utils #(if using RHEL/CentOS)
        state: present
      when: ansible_facts["os_family"] == "RedHat"
    - name: install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present
    - name: start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
    - name: allow NFS through firewall
      ansible.posix.firewalld:
        service: nfs
        permanent: true
        state: enabled
        immediate: yes
    - name: create directory for NFS share with appropriate permissions
      ansible.builtin.file:
        path: /mnt/nfs_share
        state: directory
        mode: '1777'
    - name: add exports to /etc/exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: '/mnt/nfs_share 10.0.0.0/24(rw,sync,no_subtree_check,root_squash)'
    - name: restart nfs server and enable it to start on boot
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted
        enabled: yes