- name: config for NFS clients
  hosts: all
  tasks:
    - name: install nfs client packages
      ansible.builtin.package:
        name: 
          #- nfs-common (if using Debian/Ubuntu)
          - nfs-utils #(if using RHEL/CentOS) 
          - firewalld
        state: present
        #(working on using facts to determine which package to install based on the OS)
    - name: start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
    - name: allow NFS through firewall
      ansible.posix.firewalld:
        service: nfs
        permanent: true
        state: enabled
        immediate: yes
    - name: create mount point for NFS share
      ansible.builtin.file:
        path: /mnt/nfs_local
        state: directory
        mode: '0755'
    - name: mount NFS share
      ansible.posix.mount:
        src: raspi.local:/mnt/nfs_share
        path: /mnt/nfs_local
        fstype: nfs
        opts: vers=3
        state: mounted
      become: true

