- name:  Install needed packages and update packages to latest version
  hosts: all
  tasks:
    - name: install/check if installed NetworkManager,firewalld,vim
      ansible.builtin.package:
        name: 
          - NetworkManager
          - firewalld
          - vim
          - systemd
        state: present

    - name: Update packages to their latest version 
      ansible.builtin.package:
        name: "*"
        state: latest
        
